### ISSUE TITLE
[Feature] 摄像机堆叠功能 RenderCameraStack() 以及一些相关渲染器属性和相机属性

### ISSUE THREAD

**Issue by motoyinc** [motoyinc/MotoyincRenderPipeline-Lab#6]
URP写了这个功能，我也先加个这个框架吧，虽然感觉用不上

**Comment by Motoyinc** [comment]
### 相机属性类
### AdditionalCameraData
`m_cameras` - 成员字段 用于储存base类型的Camera列表
`cameraStack`  - 获取m_cameras堆

`m_cameraRenderType` - 成员属性 用于储存相机类型（base、overlay）
`renderType` - 属性 拥有获取m_cameraRenderType

`scriptableRenderer` - 属性 从Asset获取Renderer

---
### RenderData类
### ScriptableRendererData
`SetDirty( )` 方法
- 当RenderData的某些属性发生变化是，需要将渲染器标记为过期

### MotoyincLabRendererData
`m_RenderingMode`  - 储存渲染类型（Forward，Deferred）
`renderingMode`  

---

### Renderer类
### ScriptableRenderer
`SupportedCameraStackingTypes( )`  内置方法 是否支持摄像机堆叠（需要MotoyincLabRenderer重写）
`SupportsCameraStackingType( )` 接口 返回是否支持摄像机堆叠

### MotoyincLabRenderer
`m_RenderingMode `  成员属性  渲染器会从RendererData里获取

` SupportedCameraStackingTypes( )`  内置方法 是否支持摄像机堆叠

---
### Pipline
` RenderCameraStack( )`
从AdditionalCameraData中获取相机堆叠列表cameraStack（m_cameras）
在获取之前需要检查 
- RenderData里的渲染类型是否支持相机堆叠，
- AdditionalCameraData 里的摄像机类型是否支持相机堆叠
